<?php
\ebi\Conf::set([
	'ebi.Dao'=>[
		'connection'=>[
			'model.Posts'=>[
				'type'=>'ebi.DbConnector',
				'dbname'=>'data.db',
			],
		],
	],
	'ebi.Log'=>[
		'level'=>'warn',
		'file'=>dirname(__DIR__).'/work/output.log',
		'stdout'=>true,
	],
]);
